apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: memory-box-dev
resources:
  - ../../base
patches:
  - target:
      kind: Service
      name: memory-box-front
    patch: |-
      - op: add
        path: /spec/ports/0/nodePort
        value: 30084
