apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-box-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-box-front
  template:
    metadata:
      labels:
        app: memory-box-front
    spec:
      containers:
        - name: web
          image: localhost:32000/memory-box-front:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 80