apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: memory-box
  labels:
    app: memory-box
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  ingressClassName: public
  tls:
    - hosts:
        - memory-box.shop
        - www.memory-box.shop
      secretName: memory-box-shop-tls
  rules:
    - host: memory-box.shop
      http:
        paths:
          - path: /django-admin
            pathType: Prefix
            backend:
              service:
                name: memory-box-back
                port:
                  number: 80
          - path: /static
            pathType: Prefix
            backend:
              service:
                name: memory-box-back
                port:
                  number: 80
          - path: /media
            pathType: Prefix
            backend:
              service:
                name: memory-box-back
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: memory-box-back
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: memory-box-front
                port:
                  number: 80
    - host: www.memory-box.shop
      http:
        paths:
          - path: /django-admin
            pathType: Prefix
            backend:
              service:
                name: memory-box-back
                port:
                  number: 80
          - path: /static
            pathType: Prefix
            backend:
              service:
                name: memory-box-back
                port:
                  number: 80
          - path: /media
            pathType: Prefix
            backend:
              service:
                name: memory-box-back
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: memory-box-back
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: memory-box-front
                port:
                  number: 80
